namespace SemanticHub.IngestionService.Models;

/// <summary>
/// A semantically chunked piece of a document
/// </summary>
public class DocumentChunk
{
    /// <summary>
    /// Unique identifier for this chunk
    /// </summary>
    public required string Id { get; set; }

    /// <summary>
    /// Parent document ID
    /// </summary>
    public required string ParentDocumentId { get; set; }

    /// <summary>
    /// Chunk index within the parent document
    /// </summary>
    public int ChunkIndex { get; set; }

    /// <summary>
    /// Chunk title (usually derived from headers or section name)
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The text content of this chunk
    /// </summary>
    public required string Content { get; set; }

    /// <summary>
    /// Embedding vector for this chunk (generated by Azure OpenAI)
    /// </summary>
    public float[]? ContentVector { get; set; }

    /// <summary>
    /// Metadata from the parent document
    /// </summary>
    public DocumentMetadata? Metadata { get; set; }

    /// <summary>
    /// Token count for this chunk
    /// </summary>
    public int TokenCount { get; set; }

    /// <summary>
    /// Starting character position in the original document
    /// </summary>
    public int StartPosition { get; set; }

    /// <summary>
    /// Ending character position in the original document
    /// </summary>
    public int EndPosition { get; set; }
}
